// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1s_ZFSLB3PoK982cMBIDM7w2gUgfUP4',
    appId: '1:272359043574:web:6e7c88c1f2bed2117717d7',
    messagingSenderId: '272359043574',
    projectId: 'final-exam-afe5e',
    authDomain: 'final-exam-afe5e.firebaseapp.com',
    storageBucket: 'final-exam-afe5e.appspot.com',
    measurementId: 'G-LFSC3SC30V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMsH9ckhpOxILyQQpdz4SB5GFo8OD6evg',
    appId: '1:272359043574:android:9a094e4614c2bf637717d7',
    messagingSenderId: '272359043574',
    projectId: 'final-exam-afe5e',
    storageBucket: 'final-exam-afe5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZWO45hDqrrKOdQ62Y-VoJQB-6B9KMZFc',
    appId: '1:272359043574:ios:ac0c3cb2e1d7be667717d7',
    messagingSenderId: '272359043574',
    projectId: 'final-exam-afe5e',
    storageBucket: 'final-exam-afe5e.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZWO45hDqrrKOdQ62Y-VoJQB-6B9KMZFc',
    appId: '1:272359043574:ios:ac0c3cb2e1d7be667717d7',
    messagingSenderId: '272359043574',
    projectId: 'final-exam-afe5e',
    storageBucket: 'final-exam-afe5e.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb1s_ZFSLB3PoK982cMBIDM7w2gUgfUP4',
    appId: '1:272359043574:web:116664d299b70da97717d7',
    messagingSenderId: '272359043574',
    projectId: 'final-exam-afe5e',
    authDomain: 'final-exam-afe5e.firebaseapp.com',
    storageBucket: 'final-exam-afe5e.appspot.com',
    measurementId: 'G-44C7KLCLQZ',
  );
}
